# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J0pwF5qey6osgu5InMVPfGpoWBsdIzi3
"""

def kasallik_tashxisi(alomat):
  if alomat=="bosh og'riq, istima":
    return "Sizda grip bor"
  elif alomat=="qorin og'riq":
    return "Sizda spazma bor"
  else:
    return "Noaniq kasallik, Shifokorga murojaat qiling"
alomat=input("Alomaat kiriting")
natija:kasallik_tashxisi(alomat)
print(natija)

def kasallik_tashxisi(belgi):
  if belgi=="istima":
    return "Parasetamol, trimol"
  elif belgi=="qorin og'riq":
    return "Noshpa"
  elif belgi=="tish og'rig'i":
    return "Kyupen"
  elif belgi=="bo'yin og'rig'i":
    return "Sinepar aktiv gel"
  elif belgi=="Nafas bo'gilishi, tam sezmaslik":
    return "Vaksina"
  elif belgi=="oyoq og'rig'i":
    return "Genel"
  elif belgi=="Bo'g'im og'rig'i":
    return "Vazelin"
  elif belgi=="Ko'z og'rig'i":
    return "Olopatalerg"
  elif belgi=="Quloq og'rig'i":
    return "Medeksol"
  elif belgi=="Mushak og'rig'i":
    return "Analgin"
  else:
    return "Noaniq kasallik, Shifokorga murojaat qiling"
alomat=input("Alomatni kiriting ")
natija:kasallik_tashxisi(alomat)
print(natija)

def mevalar_tarjimasi(meva):
  if meva=="shaftoli":
    return "peach"
  elif meva=="anor":
    return "pomegranate"
  elif meva=="uzum":
    return "grapes"
  elif meva=="xurmo":
    return "dates"
  elif meva=="nok":
    return "Pear"
  elif meva=="gilos":
    return "cherry"
  elif meva=="malina":
    return "respberry"
  elif meva=="yong'oq":
    return "valnut"
  elif meva=="banan":
    return "banana"
  elif meva=="apelsin":
    return "orange"
  else:
    return "Noaniq meva, bog'bonga murojaat qiling"
meva=input("mevani kiriting ")
tarjima:mevalar_tarjimasi(meva)
print(meva)