# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189bCzRsTjxZVZ9huUOo1Pt7qyMTERrxi
"""

def kasallik_tashxisi(alomat):
    if alomat == "bosh og'riq, istima":
        return "Sizda grip bor"
    elif alomat == "qorin og'riq":
        return "Sizda spazma bor"
    else:
        return "Noaniq kasallik, shifokorga murojaat qiling"

def davo_tavsiyasi(belgi):
    if belgi == "istima":
        return "Parasetamol, Trimol"
    elif belgi == "qorin og'riq":
        return "Noshpa"
    elif belgi == "tish og'rig'i":
        return "Kyupen"
    elif belgi == "bo'yin og'rig'i":
        return "Sinepar Aktiv Gel"
    elif belgi == "nafas bo'gilishi, tam sezmaslik":
        return "Vaksina"
    elif belgi == "oyoq og'rig'i":
        return "Genel"
    elif belgi == "bo'g'im og'rig'i":
        return "Vazelin"
    elif belgi == "ko'z og'rig'i":
        return "Olopatalerg"
    elif belgi == "quloq og'rig'i":
        return "Medeksol"
    elif belgi == "mushak og'rig'i":
        return "Analgin"
    else:
        return "Noaniq simptom, shifokorga murojaat qiling"

alomat = input("Alomatni kiriting: ")
tashxis = kasallik_tashxisi(alomat)
print("Tashxis:", tashxis)
davo = davo_tavsiyasi(alomat)
print("Tavsiya etilgan dori:", davo)